spring:
  application:
    name: kicker
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost/kickerdb
    username: postgres
    password: postgres
    #driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
kicker:
  security:
    users:
      - name: Peter
        password: asdfAsBcrypt
      - name: matthes
        password: asdfAsBcrypt
  slack:
    postUrl: https://hooks.slack.com/services/xyz
  publicUiUrl: http://192.168.52.72/ui/
logging:
  level:
    root: INFO
    org.hibernate.engine.jdbc.env.internal: WARN
    org.springframework.security: DEBUG